### ISSUE TITLE
Solaris7 error after running  for ~20mins

### ISSUE THREAD

**Issue by kconger** [Grabulosaure/ss#3]
I get the following error after running Solaris for some time.  It repeats on the screen and stops accepting input:

WARNING: /iommu@0, 10000000/sbus@0, 10001000/espdma@5,8400000/esp@5,8800000 (esp0) :
    polled command timeout: current esp state:
esp:    State=DATA_DONE Last State=DATA 
esp:    Latched stat=0x10<XZERO> intr=0x10<BUS> fifo 0x0
esp:    last msg out: IDENTIFY: last msg in: <unknown msg> 
esp:    DMA csr=0xa0000210 <EN, INTEN>
esp:    addr=fc01300e dmacnt=0 last=fc013000 last_cnt=f000
esp:    Cmd dump for Target 0 Lun 0: 
esp:    cdblen=6, cdb=[ 0xa 0x1c 0x5c 0xa0 Oxf8 0x0 ]
esp:    pkt_state=0xf <XFER, CMD, SEL, ARB> pkt flags=0x1 pkt_statistics=0x0 
esp:    cmd_flags=0xc62 cmd_timeout=60
WARNING: /iommu@0, 10000000/sbus@0, 10001000/espdma@5,8400000/esp@5,8800000 (esp0): 
    Polled cmd failed 
WARNING: /iommu@0, 10000000/sbus@0, 10001000/espdma@5,8400000/esp@5,8800000 (esp0):
cmd dma error

![Solaris7-error](https://user-images.githubusercontent.com/389510/165372274-e38798b2-86b5-426a-8f0d-e27402473afb.jpeg)
r

**Comment by kconger** [comment]
Can't replicate with current code

**Comment by Grabulosaure** [comment]
Maybe some issue with L2TLB which is now disabled as default. I need to check compatibility with each OS.
